### PR TITLE
Update interface ResponseObject

### PR DESCRIPTION
**Pull request by chrom007**
The API also produces a medium-sized image, but it is not in the library.
If that look at this https://api.imgbb.com/

### CODE REVIEW

**Comment by TheRealBarenziah** [comment]
Thank you @chrom007 for this PR! Can't believe I missed that :)

Merging now & will run `npm publish` during upcoming weekend

**Comment by chrom007** [comment]
Oh, it looks like I found another little problem... 
GIF images do not have medium data 🤒

**Comment by chrom007** [comment]
@TheRealBarenziah Oh, it looks like I found another little problem...
GIF images do not have medium data (only image & thumb) 🤒

**Comment by TheRealBarenziah** [comment]
Thanks for the tip, I'll look into it :)

**Comment by TheRealBarenziah** [comment]
I've checked the presence of `Object` keys with the 4 file formats ImgBB seem to support:  

.jpg => image, thumb
.gif => image, thumb
.png => image, thumb, medium
.bmp => image, thumb

I'd be grateful if you could confirm those results on your side :)

This should ["fix"](https://github.com/TheRealBarenziah/imgbb-uploader/blob/dev/src/responseInterface.ts#L24) it.

**Comment by chrom007** [comment]
Yeah, its true!
Probably making the medium field optional is the best solution for you 😸

**Pull request merged**
